[package]
name = "miden-test-harness"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
libtest-mimic = "0.8.1"

[dependencies]
midenc-harness-macros = { path = "../test-macros" }
libtest-mimic = "0.8.1"

[[test]]
harness = false
name = "lib"
path = "src/lib.rs"
