[package]
name = "miden-test-use-case"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
libtest-mimic = "0.8.1"

[dependencies]
miden-harness-macros  = { path = "../test-macros" }
miden-harness-lib     = { path = "../test-lib"    }

[[test]]
harness = false
name = "foo"
